### ISSUE TITLE
Get exporting and build pipeline working correctly

### ISSUE THREAD

**Issue by fegwin** [fegwin/cotton-js#2]
Currently when you import cotton through a "yarn add cottongiturl" the components are not working

☹️

Andrew, you are the Webpack master. Wanna sort this one out?

**Comment by fegwin** [comment]
@andrewgierens wanna take a look at this? Not really sure why this is not working.

If you copy the folder into a project and import with relative paths it all works fine.

**Comment by kyrim** [comment]
I think its working now. might be able to close this @fegwin  @andrewgierens
